/* tslint:disable */
/*--------------------------------------------------------------------------------------------

*  This is an declarationsOnly mode example output of schema2ts
*  Original input is: C:\Users\Jack\Workspace\schema2ts\examples/sources/openapi-2.0-enum.yaml
*
*  Generated by:
* 	    schema2ts 0.5.0-beta.6
* 	    Typescript ^2.6.0
*
*  See syntax error in this file?
*       We are working for these features that will break schema2ts, thanks for your waiting
*--------------------------------------------------------------------------------------------*/
import { AxiosInstance } from "axios";
export interface _Response<Status, Data> {
    data: Data;
    status: Status;
    statusText: string;
    headers: any;
    request?: any;
}
export declare const _: {
    lib: AxiosInstance;
    removeEmpty(obj: any): any;
    getPathParam(url: string, params: any): string;
    request(url: string, method: string, {query, body, path, headers, bodyType}: {
        query?: any;
        body?: any;
        path?: any;
        headers?: any;
        bodyType?: "json" | "form";
    }): Promise<{
        data: any;
        headers: any;
        request: any;
        status: any;
        statusText: string;
    }>;
};
export declare var products_get_url: string;
export declare var products_get_method: string;
export declare enum Colors {
    black = "black",
    white = "white",
    red = "red",
    green = "green",
    blue = "blue",
}
export declare enum Language {
    Typescript = 0,
    Javascript = 1,
}
export interface products_get_parameter_query {
    "color": Colors;
    "lang": Language;
    "direction": "left" | "right";
    /** enum:
    *   peter: 0
    *   jack: 1 */
    "name": 0 | 1;
}
export declare function products_get(query: products_get_parameter_query): Promise<_Response<any, any>>;
